package Vista.Cruds;

import Models.Cliente;
import com.db4o.*;
import com.db4o.query.Query;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author aberr
 */
public class CRUD_Cliente extends javax.swing.JFrame {

    static ObjectContainer BaseFinal = Db4o.openFile("C:\\Users\\diego\\OneDrive\\Escritorio\\BaseTrabajoFinal\\BaseFinal.yap");

    static ArrayList<Cliente> listaCliente = new ArrayList<>();

    

    public static List<Cliente> getListaClienteBase(ObjectContainer BaseFinal) {
        List<Cliente> listaClienteBase = new ArrayList<>();
        ObjectSet<Cliente> cliente = BaseFinal.query(Cliente.class);
        for (Cliente cliente1 : cliente) {
            listaClienteBase.add(cliente1);
        }
        return listaClienteBase;
    }


    public CRUD_Cliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        lblProveedor = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        lblTipoCliente = new javax.swing.JLabel();
        txtNombresCliente = new javax.swing.JTextField();
        txtCedulaCliente = new javax.swing.JTextField();
        txtNombreUser = new javax.swing.JTextField();
        txtCorreoCliente = new javax.swing.JTextField();
        txtDireccionCliente = new javax.swing.JTextField();
        txtApellidosCliente = new javax.swing.JTextField();
        txtFechaNacimiento = new javax.swing.JTextField();
        lblEstadoCivil = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        lblFechaNacimiento = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        lblCelular = new javax.swing.JLabel();
        comboxEstadoCivil = new javax.swing.JComboBox<>();
        comboxGenero = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        txtCelularCliente = new javax.swing.JTextField();
        lblPassUser = new javax.swing.JLabel();
        txtPassUser = new javax.swing.JPasswordField();
        lblNombreUser1 = new javax.swing.JLabel();
        comboxTipoCliente = new javax.swing.JComboBox<>();
        lblFondoCRUD = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(0, 21, 27));
        jDesktopPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jDesktopPane1.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(0, 21, 27));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblProveedor.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        lblProveedor.setForeground(new java.awt.Color(255, 255, 255));
        lblProveedor.setText("CLIENTE");
        jPanel1.add(lblProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 140, 50));

        lblDireccion.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        lblDireccion.setForeground(new java.awt.Color(255, 255, 255));
        lblDireccion.setText("Direccion");
        jPanel1.add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        lblCedula.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        lblCedula.setForeground(new java.awt.Color(255, 255, 255));
        lblCedula.setText("Cedula");
        jPanel1.add(lblCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        lblNombres.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        lblNombres.setForeground(new java.awt.Color(255, 255, 255));
        lblNombres.setText("Nombres:");
        jPanel1.add(lblNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        lblTipoCliente.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        lblTipoCliente.setForeground(new java.awt.Color(255, 255, 255));
        lblTipoCliente.setText("Tipo Cliente");
        jPanel1.add(lblTipoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));

        txtNombresCliente.setBackground(new java.awt.Color(0, 21, 27));
        txtNombresCliente.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        txtNombresCliente.setForeground(new java.awt.Color(255, 255, 255));
        txtNombresCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtNombresCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 170, 20));

        txtCedulaCliente.setBackground(new java.awt.Color(0, 21, 27));
        txtCedulaCliente.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        txtCedulaCliente.setForeground(new java.awt.Color(255, 255, 255));
        txtCedulaCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtCedulaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 170, 20));

        txtNombreUser.setBackground(new java.awt.Color(0, 21, 27));
        txtNombreUser.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        txtNombreUser.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreUser.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtNombreUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreUserActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombreUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 170, 20));

        txtCorreoCliente.setBackground(new java.awt.Color(0, 21, 27));
        txtCorreoCliente.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        txtCorreoCliente.setForeground(new java.awt.Color(255, 255, 255));
        txtCorreoCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtCorreoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 170, 20));

        txtDireccionCliente.setBackground(new java.awt.Color(0, 21, 27));
        txtDireccionCliente.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        txtDireccionCliente.setForeground(new java.awt.Color(255, 255, 255));
        txtDireccionCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtDireccionCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 170, 20));

        txtApellidosCliente.setBackground(new java.awt.Color(0, 21, 27));
        txtApellidosCliente.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        txtApellidosCliente.setForeground(new java.awt.Color(255, 255, 255));
        txtApellidosCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtApellidosCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 170, 20));

        txtFechaNacimiento.setBackground(new java.awt.Color(0, 21, 27));
        txtFechaNacimiento.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        txtFechaNacimiento.setForeground(new java.awt.Color(255, 255, 255));
        txtFechaNacimiento.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 170, 20));

        lblEstadoCivil.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        lblEstadoCivil.setForeground(new java.awt.Color(255, 255, 255));
        lblEstadoCivil.setText("Estado Civil");
        jPanel1.add(lblEstadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        lblCorreo.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(255, 255, 255));
        lblCorreo.setText("Correo Electronico");
        jPanel1.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        lblGenero.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        lblGenero.setForeground(new java.awt.Color(255, 255, 255));
        lblGenero.setText("Genero");
        jPanel1.add(lblGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, 20));

        lblFechaNacimiento.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        lblFechaNacimiento.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaNacimiento.setText("Fechas de Nacimiento");
        jPanel1.add(lblFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 150, 30));

        lblApellidos.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        lblApellidos.setForeground(new java.awt.Color(255, 255, 255));
        lblApellidos.setText("Apellidos");
        jPanel1.add(lblApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        lblCelular.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        lblCelular.setForeground(new java.awt.Color(255, 255, 255));
        lblCelular.setText("Celular");
        jPanel1.add(lblCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        comboxEstadoCivil.setBackground(new java.awt.Color(0, 21, 27));
        comboxEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SOLTERO", "CASADO", "DIVORCIADO", "UNION LIBRE", "VIUDO" }));
        jPanel1.add(comboxEstadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, -1));

        comboxGenero.setBackground(new java.awt.Color(0, 21, 27));
        comboxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FEMENINO", "MASCULINO", " " }));
        jPanel1.add(comboxGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, -1, -1));

        btnRegistrar.setBackground(new java.awt.Color(0, 21, 27));
        btnRegistrar.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, -1, -1));

        btnSalir.setBackground(new java.awt.Color(0, 21, 27));
        btnSalir.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        btnSalir.setText("SALIR");
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, -1, -1));

        txtCelularCliente.setBackground(new java.awt.Color(0, 21, 27));
        txtCelularCliente.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        txtCelularCliente.setForeground(new java.awt.Color(255, 255, 255));
        txtCelularCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(txtCelularCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 170, 20));

        lblPassUser.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        lblPassUser.setForeground(new java.awt.Color(255, 255, 255));
        lblPassUser.setText("Contraseña");
        jPanel1.add(lblPassUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, -1, -1));

        txtPassUser.setBackground(new java.awt.Color(0, 21, 27));
        jPanel1.add(txtPassUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 170, -1));

        lblNombreUser1.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        lblNombreUser1.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreUser1.setText("Nombe Usuario");
        jPanel1.add(lblNombreUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, -1, -1));

        comboxTipoCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboxTipoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxTipoClienteActionPerformed(evt);
            }
        });
        jPanel1.add(comboxTipoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, -1, -1));

        lblFondoCRUD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CRUD_ORIGINAL.jpg"))); // NOI18N
        lblFondoCRUD.setText("ASASADAS");
        jPanel1.add(lblFondoCRUD, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -90, 740, 680));

        jDesktopPane1.add(jPanel1, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreUserActionPerformed
public void GuardarCliente(ObjectContainer BaseFinal, String tipo_Cliente, String nombreUsuario, String password,
            String cedula, String nombres, String apellidos, String direccion, String correo, String celular, String genero, String fechaNacimiento, String estadoCivil) {

        Cliente cliente = new Cliente( );

        if (VerificarCliente(BaseFinal, nombreUsuario) == 0) {

            BaseFinal.set(cliente);

            JOptionPane.showMessageDialog(this, "Cliente Guardado");

        } else {

            JOptionPane.showMessageDialog(this, "Ya existe el Usuario,Intente otro Usuario");
        }
    }

    public static int VerificarCliente(ObjectContainer BaseFinal, String user) {

        Cliente PBuscar = new Cliente(user);

        ObjectSet resultado = BaseFinal.get(PBuscar);//objeto tipo registro

        return resultado.size();
    }
    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

        boolean usuarioRepetido = false;

        Query cliente = BaseFinal.query();
        cliente.constrain(Cliente.class);
        cliente.descend("usuario_Cliente").constrain(txtNombreUser.getText());
        ObjectSet<Cliente> result = cliente.execute();

        if (result.size() > 0) {
            JOptionPane.showMessageDialog(this, "Usuario ya registrado");
            usuarioRepetido = true;
        }

        if (!usuarioRepetido) {

            String auxcedula = txtCedulaCliente.getText();
            String auxnombre = txtNombresCliente.getText();
            String auxapellido = txtApellidosCliente.getText();
            String auxdireccion = txtDireccionCliente.getText();
            String auxcorreo = txtCorreoCliente.getText();
            String auxcelular = txtCelularCliente.getText();
            String auxfechanacimiento = txtFechaNacimiento.getText();
            String auxestadocivil = (String) comboxEstadoCivil.getSelectedItem();
            String auxgenero = (String) comboxGenero.getSelectedItem();
            String auxtipocliente = (String) comboxTipoCliente.getSelectedItem();
            String auxnombreuser = txtNombreUser.getText();
            String auxpassuser = txtPassUser.getText();

            Cliente cliente1 = new Cliente();

            cliente1.setCedula(auxcedula);
            cliente1.setNombres(auxnombre);
            cliente1.setApellidos(auxapellido);
            cliente1.setDireccion(auxdireccion);
            cliente1.setCorreo(auxcorreo);
            cliente1.setCelular(auxcelular);
            cliente1.setFechaNacimiento(auxfechanacimiento);
            cliente1.setEstadoCivil(auxestadocivil);
            cliente1.setGenero(auxgenero);
            cliente1.setTipo_Cliente(auxtipocliente);
            cliente1.setUsuario(auxnombreuser);
            cliente1.setPassword(auxpassuser);
            
            //agrega a la base de datos
            
            GuardarCliente(BaseFinal, auxtipocliente, auxnombreuser, auxpassuser, auxcedula, auxnombre, auxapellido, auxdireccion,
                    auxcorreo, auxcelular, auxgenero, auxfechanacimiento, auxestadocivil);
        }

        
        txtCedulaCliente.setText("");
        txtNombresCliente.setText("");
        txtApellidosCliente.setText("");
        txtDireccionCliente.setText("");
        txtCorreoCliente.setText("");
        txtCelularCliente.setText("");
        txtFechaNacimiento.setText("");
        comboxEstadoCivil.setSelectedIndex(-1);
        comboxGenero.setSelectedIndex(-1);
        comboxTipoCliente.setSelectedIndex(-1);
        txtNombreUser.setText("");
        txtPassUser.setText("");
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void comboxTipoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxTipoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxTipoClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUD_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUD_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUD_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUD_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUD_Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> comboxEstadoCivil;
    private javax.swing.JComboBox<String> comboxGenero;
    private javax.swing.JComboBox<String> comboxTipoCliente;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblEstadoCivil;
    private javax.swing.JLabel lblFechaNacimiento;
    private javax.swing.JLabel lblFondoCRUD;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblNombreUser1;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblPassUser;
    private javax.swing.JLabel lblProveedor;
    private javax.swing.JLabel lblTipoCliente;
    private javax.swing.JTextField txtApellidosCliente;
    private javax.swing.JTextField txtCedulaCliente;
    private javax.swing.JTextField txtCelularCliente;
    private javax.swing.JTextField txtCorreoCliente;
    private javax.swing.JTextField txtDireccionCliente;
    private javax.swing.JTextField txtFechaNacimiento;
    private javax.swing.JTextField txtNombreUser;
    private javax.swing.JTextField txtNombresCliente;
    private javax.swing.JPasswordField txtPassUser;
    // End of variables declaration//GEN-END:variables
}
