
package Vista.Cruds;

import Models.*;
import com.db4o.Db4o;
import com.db4o.ObjectContainer;
import com.db4o.ObjectSet;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;


public class CRUD_Producto extends javax.swing.JFrame {

    public CRUD_Producto() {
        initComponents();
        pnlBotones.setOpaque(false);
        btnModificar.setVisible(false);
        btnEliminar.setVisible(false);
//        transparente();
    }
    
    public final void transparente() {
        txtCodigoProducto.setVisible(true);
        txtCodigoProducto.setOpaque(false);
        txtPrecioProducto.setVisible(true);
        txtPrecioProducto.setOpaque(false);
        txtNombreProducto.setVisible(true);
        txtNombreProducto.setOpaque(false);
        
//        
//        btnBotoncito2.setVisible(true);
//        btnBotoncito2.setOpaque(false);
//        btnBotoncito2.setContentAreaFilled(false);
//        btnBotoncito2.setBorderPainted(false);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        lblProveedor = new javax.swing.JLabel();
        lblPrecioProducto = new javax.swing.JLabel();
        txtPrecioProducto = new javax.swing.JTextField();
        lblNombreProducto = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JTextField();
        txtCodigoProducto = new javax.swing.JTextField();
        lblCodigooProducto = new javax.swing.JLabel();
        sprCodigoProducto = new javax.swing.JSeparator();
        sprPrecioProducto = new javax.swing.JSeparator();
        sprNombreProducto = new javax.swing.JSeparator();
        pnlBotones = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        txtExistenciaMaxima = new javax.swing.JTextField();
        lblExistenciaMaxima = new javax.swing.JLabel();
        lblCodigoocategoria = new javax.swing.JLabel();
        sprCodigoCategoria = new javax.swing.JSeparator();
        lblNumeroProductos = new javax.swing.JLabel();
        txtNumeroProductos = new javax.swing.JTextField();
        txtCodigoCategoria = new javax.swing.JTextField();
        sprNumeroProductos = new javax.swing.JSeparator();
        sprExistenciaMaxima = new javax.swing.JSeparator();
        lblExistenciaMinima = new javax.swing.JLabel();
        txtExistenciaMinima = new javax.swing.JTextField();
        sprExistenciaMinima = new javax.swing.JSeparator();
        txtDescripcion = new javax.swing.JTextField();
        sprDescripcion = new javax.swing.JSeparator();
        lblDescripcion = new javax.swing.JLabel();
        lblProveedorID = new javax.swing.JLabel();
        txtProveedorID = new javax.swing.JTextField();
        sprProveedorID = new javax.swing.JSeparator();
        lblFondoCRUD = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(0, 21, 27));
        jDesktopPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jDesktopPane1.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(0, 21, 27));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblProveedor.setFont(new java.awt.Font("Eras Bold ITC", 3, 48)); // NOI18N
        lblProveedor.setForeground(new java.awt.Color(255, 255, 255));
        lblProveedor.setText("PRODUCTO");
        jPanel1.add(lblProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 440, 80));

        lblPrecioProducto.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        lblPrecioProducto.setForeground(new java.awt.Color(255, 255, 255));
        lblPrecioProducto.setText("Precio:");
        jPanel1.add(lblPrecioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        txtPrecioProducto.setBackground(new java.awt.Color(0, 21, 27));
        txtPrecioProducto.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        txtPrecioProducto.setForeground(new java.awt.Color(255, 255, 255));
        txtPrecioProducto.setBorder(null);
        txtPrecioProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioProductoActionPerformed(evt);
            }
        });
        txtPrecioProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioProductoKeyTyped(evt);
            }
        });
        jPanel1.add(txtPrecioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 250, 30));

        lblNombreProducto.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        lblNombreProducto.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreProducto.setText("Nombre:");
        jPanel1.add(lblNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        txtNombreProducto.setBackground(new java.awt.Color(0, 21, 27));
        txtNombreProducto.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        txtNombreProducto.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreProducto.setBorder(null);
        txtNombreProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreProductoKeyTyped(evt);
            }
        });
        jPanel1.add(txtNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 250, 30));

        txtCodigoProducto.setBackground(new java.awt.Color(0, 21, 27));
        txtCodigoProducto.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        txtCodigoProducto.setForeground(new java.awt.Color(255, 255, 255));
        txtCodigoProducto.setBorder(null);
        jPanel1.add(txtCodigoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 250, 30));

        lblCodigooProducto.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        lblCodigooProducto.setForeground(new java.awt.Color(255, 255, 255));
        lblCodigooProducto.setText("Código:");
        jPanel1.add(lblCodigooProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        sprCodigoProducto.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(sprCodigoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 250, 20));

        sprPrecioProducto.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(sprPrecioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 250, 20));

        sprNombreProducto.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(sprNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 250, 20));

        pnlBotones.setBackground(new java.awt.Color(0, 21, 27));
        pnlBotones.setLayout(new java.awt.GridBagLayout());

        btnEliminar.setBackground(new java.awt.Color(0, 21, 27));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setToolTipText("Eliminar Proveedor seleccionado");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 6);
        pnlBotones.add(btnEliminar, gridBagConstraints);

        btnModificar.setBackground(new java.awt.Color(0, 21, 27));
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("Modificar/Guardar");
        btnModificar.setToolTipText("Para guardar cambios (Si hubiere)");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        pnlBotones.add(btnModificar, gridBagConstraints);

        btnRegistrar.setBackground(new java.awt.Color(0, 21, 27));
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.setToolTipText("Ingrese todos los campos");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        pnlBotones.add(btnRegistrar, gridBagConstraints);

        btnBuscar.setBackground(new java.awt.Color(0, 21, 27));
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.setToolTipText("Ingrese el codigo de proveedor");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 6);
        pnlBotones.add(btnBuscar, gridBagConstraints);

        jPanel1.add(pnlBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 230, -1));

        btnSalir.setBackground(new java.awt.Color(0, 21, 27));
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/Salir 30x30.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 120, 40));

        txtExistenciaMaxima.setBackground(new java.awt.Color(0, 21, 27));
        txtExistenciaMaxima.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        txtExistenciaMaxima.setForeground(new java.awt.Color(255, 255, 255));
        txtExistenciaMaxima.setBorder(null);
        txtExistenciaMaxima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExistenciaMaximaActionPerformed(evt);
            }
        });
        txtExistenciaMaxima.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtExistenciaMaximaKeyTyped(evt);
            }
        });
        jPanel1.add(txtExistenciaMaxima, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 250, 30));

        lblExistenciaMaxima.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        lblExistenciaMaxima.setForeground(new java.awt.Color(255, 255, 255));
        lblExistenciaMaxima.setText("Existencia maxima:");
        jPanel1.add(lblExistenciaMaxima, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        lblCodigoocategoria.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        lblCodigoocategoria.setForeground(new java.awt.Color(255, 255, 255));
        lblCodigoocategoria.setText("Código de categoría:");
        jPanel1.add(lblCodigoocategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        sprCodigoCategoria.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(sprCodigoCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 250, 20));

        lblNumeroProductos.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        lblNumeroProductos.setForeground(new java.awt.Color(255, 255, 255));
        lblNumeroProductos.setText("Numero de productos:");
        jPanel1.add(lblNumeroProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        txtNumeroProductos.setBackground(new java.awt.Color(0, 21, 27));
        txtNumeroProductos.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        txtNumeroProductos.setForeground(new java.awt.Color(255, 255, 255));
        txtNumeroProductos.setBorder(null);
        txtNumeroProductos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroProductosKeyTyped(evt);
            }
        });
        jPanel1.add(txtNumeroProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 250, 30));

        txtCodigoCategoria.setBackground(new java.awt.Color(0, 21, 27));
        txtCodigoCategoria.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        txtCodigoCategoria.setForeground(new java.awt.Color(255, 255, 255));
        txtCodigoCategoria.setBorder(null);
        jPanel1.add(txtCodigoCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 250, 30));

        sprNumeroProductos.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(sprNumeroProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 250, 20));

        sprExistenciaMaxima.setForeground(new java.awt.Color(255, 255, 255));
        sprExistenciaMaxima.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sprExistenciaMaximaKeyTyped(evt);
            }
        });
        jPanel1.add(sprExistenciaMaxima, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 250, 20));

        lblExistenciaMinima.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        lblExistenciaMinima.setForeground(new java.awt.Color(255, 255, 255));
        lblExistenciaMinima.setText("Existencia minima:");
        jPanel1.add(lblExistenciaMinima, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        txtExistenciaMinima.setBackground(new java.awt.Color(0, 21, 27));
        txtExistenciaMinima.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        txtExistenciaMinima.setForeground(new java.awt.Color(255, 255, 255));
        txtExistenciaMinima.setBorder(null);
        txtExistenciaMinima.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtExistenciaMinimaKeyTyped(evt);
            }
        });
        jPanel1.add(txtExistenciaMinima, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 250, 30));

        sprExistenciaMinima.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(sprExistenciaMinima, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 250, 20));

        txtDescripcion.setBackground(new java.awt.Color(0, 21, 27));
        txtDescripcion.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        txtDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        txtDescripcion.setBorder(null);
        txtDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescripcionKeyTyped(evt);
            }
        });
        jPanel1.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 250, 30));

        sprDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(sprDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 250, 20));

        lblDescripcion.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        lblDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        lblDescripcion.setText("Descripcion:");
        jPanel1.add(lblDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        lblProveedorID.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        lblProveedorID.setForeground(new java.awt.Color(255, 255, 255));
        lblProveedorID.setText("ID proveedor:");
        jPanel1.add(lblProveedorID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        txtProveedorID.setBackground(new java.awt.Color(0, 21, 27));
        txtProveedorID.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        txtProveedorID.setForeground(new java.awt.Color(255, 255, 255));
        txtProveedorID.setBorder(null);
        txtProveedorID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProveedorIDActionPerformed(evt);
            }
        });
        jPanel1.add(txtProveedorID, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 250, 30));

        sprProveedorID.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(sprProveedorID, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 250, 20));

        lblFondoCRUD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CRUD_ORIGINAL.jpg"))); // NOI18N
        jPanel1.add(lblFondoCRUD, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 470));

        jDesktopPane1.add(jPanel1, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrecioProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioProductoActionPerformed

    
   
    
    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        //buscamos a proveedor de la base
        for (int i = 0; i < listaProductosBase.size(); i++) {
            if (txtCodigoProducto.getText().equals(listaProductosBase.get(i).getCodigo_Producto())) {
                Boolean valido = false;//creamos una bandera para validar datos
                if (valido = txtPrecioProducto.getText().matches("\\d+(\\.\\d+)?")) {
                    if (valido = txtNumeroProductos.getText().matches("\\d+")) {
                        if (valido = txtExistenciaMaxima.getText().matches("\\d+")) {
                            if (valido = txtExistenciaMinima.getText().matches("\\d+")) {
                                String precioTexto = txtPrecioProducto.getText();
                                Double precio = Double.parseDouble(precioTexto);
                                String numeroP = txtNumeroProductos.getText();
                                int numero = Integer.parseInt(numeroP);
                                String exist1 = txtExistenciaMaxima.getText();
                                int existenciaMax = Integer.parseInt(exist1);
                                String exist2 = txtExistenciaMinima.getText();
                                int existenciaMin = Integer.parseInt(exist2);
                                
                                
                                Producto encontrado = new Producto(txtCodigoProducto.getText(), null,0.0, null, 0,0,0,null,null);//generamos una persona con la cedula para buscar
                        ObjectSet resultado = BaseFinal.get(encontrado);//buscamos en la base
                        if (!resultado.isEmpty()) {
                            resultado.forEach((obj) -> {
                                BaseFinal.delete(obj);//eliminamos cada objeto encontrado
                            });
                        } else {
                            JOptionPane.showMessageDialog(null, "Producto no encontrada en la BD");
                        }
                        //una vez eliminado procede a guardar para  "Modificar"

                                guardarProducto(BaseFinal, null, txtNombreProducto.getText(), precio, txtCodigoCategoria.getText(), numero, existenciaMax, existenciaMin, txtDescripcion.getText(), txtProveedorID.getText());
                            } else {
                                JOptionPane.showMessageDialog(this, "Ingrese un numero entero positivo de  existencia minima de productos ej: 10");
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "Ingrese un numero entero positivo de  existencia maxima de productos ej: 10");
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Ingrese un numero entero positivo de productos ej: 10");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Ingrese un precio en decimales ej: 10.25");
                }
                
                
            }
        }
        //reset campos
        resetCampos();
        //visualizar botones necesarios
        btnBuscar.setVisible(true);
        btnRegistrar.setVisible(true);
        btnModificar.setVisible(false);
        btnEliminar.setVisible(false);
        txtCodigoProducto.setEnabled(true);
        
    }//GEN-LAST:event_btnModificarActionPerformed

    public static List<Producto> getListaProductosBase(ObjectContainer BaseFinal) {//metodo para obtener la lista de la base
        List<Producto> listaProductosBase = new ArrayList<>();
        ObjectSet<Producto> productos = BaseFinal.query(Producto.class);
        for (Producto producto : productos) {
            listaProductosBase.add(producto);
        }
        return listaProductosBase;
    }
    
    // Nombrar la lista con el uso del metodo anterior
    List<Producto> listaProductosBase = getListaProductosBase(BaseFinal);
    
    public static int verificarProducto(ObjectContainer BaseFinal,String codigo_Producto, String nombre_Producto, Double precio_Producto, String codigo_categoria_Producto, int numeroProductos_Producto, int existrenciaMaxima_Producto, int existenciaMinima_Producto, String descripcion_Producto, String ID_Proveedor_Producto) {
        // Crear un nuevo objeto  para usar como plantilla de búsqueda
        Producto BuscarProd = new Producto(codigo_Producto, null,0.0, null, 0,0,0, null, null);//se ingreesará el valor del codigo y el resto nulo
        // Obtener todos los objetos que coincidan con la plantilla de búsqueda
        ObjectSet resultado = BaseFinal.get(BuscarProd);//se obtendra resultado que coincida con el codigo
        return resultado.size();//devolvera el numero de coincidencias
    }
    
    
    
    public static void guardarProducto(ObjectContainer BaseFinal, String codigo_Producto, String nombre_Producto, Double precio_Producto, String codigo_categoria_Producto, int numeroProductos_Producto, int existrenciaMaxima_Producto, int existenciaMinima_Producto, String descripcion_Producto, String ID_Proveedor_Producto) {

        Producto producto1 = new Producto(codigo_Producto, nombre_Producto, precio_Producto, codigo_categoria_Producto, numeroProductos_Producto, existrenciaMaxima_Producto, existenciaMinima_Producto, descripcion_Producto, ID_Proveedor_Producto);

        if (verificarProducto(BaseFinal, codigo_Producto, null, 0.0, null, 0, 0, 0, null, null) == 0) {//mandamos a verificar con el codigo
            if (true) {
            }
            BaseFinal.set(producto1);
            JOptionPane.showMessageDialog(null, "Producto guardado");
        } else {
            JOptionPane.showMessageDialog(null, "Producto ya existe en la BD");
        }
    }
    
    
    
    public static int verificarProveedor(ObjectContainer BaseFinal,String codigo_proveedor, String tipo_proveedor, String nombre_proveedor) {
        // Crear un nuevo objeto Clientes para usar como plantilla de búsqueda
        Proveedor BuscarProveedor = new Proveedor(codigo_proveedor, null, null);//se ingreesará el valor del codigo y el resto nulo
        // Obtener todos los objetos que coincidan con la plantilla de búsqueda
        ObjectSet resultado = BaseFinal.get(BuscarProveedor);//se obtendra resultado que coincida con el codigo
        return resultado.size();//devolvera el numero de coincidencias
    }
    
    
//    private void mostrarDatos(ObjectContainer base) {
//    jTable1.setEnabled(true);
//        //Guardamos en "resultado" todos proveedores de la base de Datos
//        ObjectSet<Producto> resultado = base.get(Producto.class);
//        //Creo una matriz
//        String matriz[][] = new String[resultado.size()][9];
//        int i = 0;
//        for (Producto miProducto : resultado) {//iteramos en cada elemento de "resultado"
//            matriz[i][0] = miProducto.getCodigo_Producto();
//            matriz[i][1] = miProducto.getNombre_Producto();
//            matriz[i][2] = miProducto.getPrecio_Producto().toString();
//            matriz[i][3] = miProducto.getCodigo_categoria_Producto();
//            matriz[i][4] =miProducto.getNumeroProductos_Producto().toString();
//            matriz[i][5] = miProducto.getExistrenciaMaxima_Producto().toString();
//            i++;
//        }
//
//        // datos configurados
//        jTable1.setModel(new javax.swing.table.DefaultTableModel(matriz, new String[]{"Codigo", "Nombre ","Tipo de Proveedor"}));
//        jTable1.setEnabled(false);
//    }
    
    private void resetCampos(){
        txtCodigoProducto.setText("");
        txtNombreProducto.setText("");
        txtPrecioProducto.setText("");
        txtCodigoCategoria.setText("");
        txtNumeroProductos.setText("");
        txtExistenciaMaxima.setText("");
        txtExistenciaMinima.setText("");
        txtDescripcion.setText("");
        txtProveedorID.setText("");        
    }
    
    
    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        //verificamos que no haya el mismo codigo
        Boolean encontrado = false;
        if (listaProductosBase.size() > 0) {
            for (int i = 0; i < listaProductosBase.size(); i++) {
                if (listaProductosBase.get(i).getNombre_Producto().equalsIgnoreCase(txtNombreProducto.getText())) {
                    JOptionPane.showMessageDialog(this, "YA EXISTE  EL PRODUCTO " + listaProductosBase.get(i).getCodigo_Producto());
                    encontrado = true;
                    resetCampos();
                }
            }

        }
        Boolean valido = false;//creamos una bandera para validar datos
        if (valido = txtPrecioProducto.getText().matches("\\d+(\\.\\d+)?")) {
            if (valido = txtNumeroProductos.getText().matches("\\d+")) {
                if (valido = txtExistenciaMaxima.getText().matches("\\d+")) {
                    if (valido = txtExistenciaMinima.getText().matches("\\d+")) {
                        String precioTexto = txtPrecioProducto.getText();
                        Double precio = Double.parseDouble(precioTexto);
                        String numeroP = txtNumeroProductos.getText();
                        int numero = Integer.parseInt(numeroP);
                        String exist1 = txtExistenciaMaxima.getText();
                        int existenciaMax = Integer.parseInt(exist1);
                        String exist2 = txtExistenciaMinima.getText();
                        int existenciaMin = Integer.parseInt(exist2);

                        guardarProducto(BaseFinal, null, txtNombreProducto.getText(), precio, txtCodigoCategoria.getText(), numero, existenciaMax, existenciaMin, txtDescripcion.getText(), txtProveedorID.getText());
                    } else {
                        JOptionPane.showMessageDialog(this, "Ingrese un numero entero positivo de  existencia minima de productos ej: 10");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Ingrese un numero entero positivo de  existencia maxima de productos ej: 10");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Ingrese un numero entero positivo de productos ej: 10");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese un precio en decimales ej: 10.25");
        }
        resetCampos();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    
    public Producto buscarProductoPorCodigo(ObjectContainer base, String codigo) {
        Producto producto = null;
        ObjectSet<Producto> productos = base.query(Producto.class);
        for (Producto p : productos) {
            if (p.getCodigo_Producto().equals(codigo)) {
                producto = p;
                break;
            }
        }
        return producto;
    }
    
    
    
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // Buscar una Proveedior por codigo
        Producto miProd = buscarProductoPorCodigo(BaseFinal, txtCodigoProducto.getText());
        if (miProd != null) {//si encontramos resultados (no seria nulo)
            //recibimos los valores del objeto encontrado y lo pasamos a los campos
            txtNombreProducto.setText(miProd.getNombre_Producto());
            txtPrecioProducto.setText(miProd.getPrecio_Producto().toString());
            txtCodigoCategoria.setText(miProd.getCodigo_categoria_Producto());
            txtNumeroProductos.setText(String.valueOf(miProd.getNumeroProductos_Producto()));
            txtExistenciaMaxima.setText(String.valueOf(miProd.getExistrenciaMaxima_Producto()));
            txtExistenciaMinima.setText(String.valueOf(miProd.getExistenciaMinima_Producto()));
            txtDescripcion.setText(miProd.getDescripcion_Producto());
            txtProveedorID.setText(miProd.getID_Proveedor_Producto());
            
            JOptionPane.showMessageDialog(this, "Persona encontrada");
            txtCodigoProducto.setEnabled(false);
            btnRegistrar.setVisible(false);
            btnBuscar.setVisible(false);
            btnEliminar.setVisible(true);
            btnModificar.setVisible(true);
            
        } else {
            JOptionPane.showMessageDialog(this, "No se encontro al proveedor con codigo "+txtCodigoProducto.getText());
            
        }
        resetCampos();        
    }//GEN-LAST:event_btnBuscarActionPerformed

    public static void cerrar_BD(ObjectContainer BaseFinal) {
        BaseFinal.close();
        System.exit(0);
    }
    
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.setVisible(false);
        cerrar_BD(BaseFinal);  
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        Producto ProdEncontrado = new Producto(txtCodigoProducto.getText(), null, 0.0, null, 0, 0,0, null, null);//generamos un objeto con codigo para buscar
        ObjectSet resultado = BaseFinal.get(ProdEncontrado);//buscamos en la base
        Boolean encontrado = false;//bandera para informar que no se encontro coincidencias
        if (!resultado.isEmpty()) {
            int respuesta = JOptionPane.showConfirmDialog(null, "Esta seguro que desea eliminar el producto " + txtNombreProducto.getText() + "?", "Eliminar Producto", JOptionPane.YES_NO_OPTION);
            if (respuesta == JOptionPane.YES_OPTION) {
                // Eliminar la 
                for (Object obj : resultado) {
                    BaseFinal.delete(obj);//eliminamos cada objeto encontrado
                }
                JOptionPane.showMessageDialog(null, "Producto eliminado");
                encontrado = true;
            } else {
                // No eliminar la 
                JOptionPane.showMessageDialog(null, "Operación cancelada");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Producto no encontrado en la BD");
        }
        //reset campos
        resetCampos();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtExistenciaMaximaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExistenciaMaximaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExistenciaMaximaActionPerformed

    private void txtProveedorIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProveedorIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProveedorIDActionPerformed

    private void txtNombreProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreProductoKeyTyped
        char x = evt.getKeyChar();
        if (Character.isDigit(x)) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingrese solo letras");
        }
    }//GEN-LAST:event_txtNombreProductoKeyTyped

    private void txtPrecioProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioProductoKeyTyped
        char x = evt.getKeyChar();
        if (Character.isLetter(x)) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingrese solo números");
        }
    }//GEN-LAST:event_txtPrecioProductoKeyTyped

    private void txtNumeroProductosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroProductosKeyTyped
        char x = evt.getKeyChar();
        if (Character.isLetter(x)) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingrese solo números");
        }
    }//GEN-LAST:event_txtNumeroProductosKeyTyped

    private void txtExistenciaMaximaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtExistenciaMaximaKeyTyped
        char x = evt.getKeyChar();
        if (Character.isLetter(x)) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingrese solo números");
        }
    }//GEN-LAST:event_txtExistenciaMaximaKeyTyped

    private void sprExistenciaMaximaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sprExistenciaMaximaKeyTyped
        //a
    }//GEN-LAST:event_sprExistenciaMaximaKeyTyped

    private void txtExistenciaMinimaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtExistenciaMinimaKeyTyped
        char x = evt.getKeyChar();
        if (Character.isLetter(x)) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingrese solo números");
        }
    }//GEN-LAST:event_txtExistenciaMinimaKeyTyped

    private void txtDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionKeyTyped
        char x = evt.getKeyChar();
        if (Character.isDigit(x)) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingrese solo letras");
        }
    }//GEN-LAST:event_txtDescripcionKeyTyped

    static ObjectContainer BaseFinal = Db4o.openFile("C:\\Users\\aberr\\Escritorio\\POO\\BASE DE PROYECTO\\BaseFinal.yap");
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUD_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUD_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUD_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUD_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUD_Producto().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCodigooProducto;
    private javax.swing.JLabel lblCodigoocategoria;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblExistenciaMaxima;
    private javax.swing.JLabel lblExistenciaMinima;
    private javax.swing.JLabel lblFondoCRUD;
    private javax.swing.JLabel lblNombreProducto;
    private javax.swing.JLabel lblNumeroProductos;
    private javax.swing.JLabel lblPrecioProducto;
    private javax.swing.JLabel lblProveedor;
    private javax.swing.JLabel lblProveedorID;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JSeparator sprCodigoCategoria;
    private javax.swing.JSeparator sprCodigoProducto;
    private javax.swing.JSeparator sprDescripcion;
    private javax.swing.JSeparator sprExistenciaMaxima;
    private javax.swing.JSeparator sprExistenciaMinima;
    private javax.swing.JSeparator sprNombreProducto;
    private javax.swing.JSeparator sprNumeroProductos;
    private javax.swing.JSeparator sprPrecioProducto;
    private javax.swing.JSeparator sprProveedorID;
    private javax.swing.JTextField txtCodigoCategoria;
    private javax.swing.JTextField txtCodigoProducto;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtExistenciaMaxima;
    private javax.swing.JTextField txtExistenciaMinima;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtNumeroProductos;
    private javax.swing.JTextField txtPrecioProducto;
    private javax.swing.JTextField txtProveedorID;
    // End of variables declaration//GEN-END:variables
}
