/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Cruds;

import Models.Vehiculo;
import static Vista.Cruds.CRUD_Proveedor.BaseFinal;
import com.db4o.ObjectContainer;
import com.db4o.ObjectSet;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author aberr
 */
public class CRUD_Vehiculo extends javax.swing.JFrame {

    /**
     * Creates new form CRUD_Proveedor
     */
    public CRUD_Vehiculo() {
        initComponents();
        pnlBotones.setOpaque(false);//hacemos el panel transparente
        mostrarDatos(BaseFinal);
        btnModificar.setVisible(false);
        btnEliminar.setVisible(false);
//        transparente();
    }
    
    public final void transparente() {
        txtPlaca.setVisible(true);
        txtPlaca.setOpaque(false);
        txtColor.setVisible(true);
        txtColor.setOpaque(false);
        txtModelo.setVisible(true);
        txtModelo.setOpaque(false);
        txtAñoFab.setVisible(true);
        txtAñoFab.setOpaque(false);
        
//        
//        btnBotoncito2.setVisible(true);
//        btnBotoncito2.setOpaque(false);
//        btnBotoncito2.setContentAreaFilled(false);
//        btnBotoncito2.setBorderPainted(false);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        lblVehiculo = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        lblPlaca = new javax.swing.JLabel();
        sprPlaca = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnlBotones = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblColor = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        sprColor = new javax.swing.JSeparator();
        txtAñoFab = new javax.swing.JTextField();
        sprAñoFab = new javax.swing.JSeparator();
        lblAñoFabric = new javax.swing.JLabel();
        cmbMarca = new javax.swing.JComboBox<>();
        txtModelo = new javax.swing.JTextField();
        sprModelo = new javax.swing.JSeparator();
        lblFondoCRUD = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(0, 21, 27));
        jDesktopPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jDesktopPane1.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(0, 21, 27));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblVehiculo.setFont(new java.awt.Font("Eras Bold ITC", 3, 48)); // NOI18N
        lblVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        lblVehiculo.setText("Vehiculo");
        jPanel1.add(lblVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 440, 80));

        lblMarca.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        lblMarca.setForeground(new java.awt.Color(255, 255, 255));
        lblMarca.setText("Marca:");
        jPanel1.add(lblMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        lblModelo.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        lblModelo.setForeground(new java.awt.Color(255, 255, 255));
        lblModelo.setText("Modelo:");
        jPanel1.add(lblModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        txtPlaca.setBackground(new java.awt.Color(0, 21, 27));
        txtPlaca.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        txtPlaca.setForeground(new java.awt.Color(255, 255, 255));
        txtPlaca.setBorder(null);
        jPanel1.add(txtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 360, 30));

        lblPlaca.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        lblPlaca.setForeground(new java.awt.Color(255, 255, 255));
        lblPlaca.setText("Placa:");
        jPanel1.add(lblPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        sprPlaca.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(sprPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 360, 20));

        jTable1.setBackground(new java.awt.Color(0, 21, 27));
        jTable1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 700, 130));

        pnlBotones.setBackground(new java.awt.Color(0, 21, 27));
        pnlBotones.setLayout(new java.awt.GridBagLayout());

        btnEliminar.setBackground(new java.awt.Color(0, 21, 27));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setToolTipText("Eliminar Proveedor seleccionado");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 6);
        pnlBotones.add(btnEliminar, gridBagConstraints);

        btnModificar.setBackground(new java.awt.Color(0, 21, 27));
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("Modificar/Guardar");
        btnModificar.setToolTipText("Para guardar cambios (Si hubiere)");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        pnlBotones.add(btnModificar, gridBagConstraints);

        btnRegistrar.setBackground(new java.awt.Color(0, 21, 27));
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.setToolTipText("Ingrese todos los campos");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        pnlBotones.add(btnRegistrar, gridBagConstraints);

        btnBuscar.setBackground(new java.awt.Color(0, 21, 27));
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.setToolTipText("Ingrese el codigo de proveedor");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 6);
        pnlBotones.add(btnBuscar, gridBagConstraints);

        jPanel1.add(pnlBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 230, -1));

        btnSalir.setBackground(new java.awt.Color(0, 21, 27));
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconos/Salir 30x30.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setBorder(null);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, 80, 40));

        lblColor.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        lblColor.setForeground(new java.awt.Color(255, 255, 255));
        lblColor.setText("Color");
        jPanel1.add(lblColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        txtColor.setBackground(new java.awt.Color(0, 21, 27));
        txtColor.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        txtColor.setForeground(new java.awt.Color(255, 255, 255));
        txtColor.setBorder(null);
        txtColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColorActionPerformed(evt);
            }
        });
        txtColor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtColorKeyTyped(evt);
            }
        });
        jPanel1.add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 360, 30));

        sprColor.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(sprColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 360, 20));

        txtAñoFab.setBackground(new java.awt.Color(0, 21, 27));
        txtAñoFab.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        txtAñoFab.setForeground(new java.awt.Color(255, 255, 255));
        txtAñoFab.setBorder(null);
        jPanel1.add(txtAñoFab, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 270, 30));

        sprAñoFab.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(sprAñoFab, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 270, 20));

        lblAñoFabric.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        lblAñoFabric.setForeground(new java.awt.Color(255, 255, 255));
        lblAñoFabric.setText("Año Fabricacion:");
        jPanel1.add(lblAñoFabric, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, 30));

        cmbMarca.setBackground(new java.awt.Color(0, 21, 27));
        cmbMarca.setForeground(new java.awt.Color(255, 255, 255));
        cmbMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHEVROLET", "NISSAN", "JAC", "SUZUKI", "KIA", "MAZDA", "FORD", "TOYOTA" }));
        jPanel1.add(cmbMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 360, 30));

        txtModelo.setBackground(new java.awt.Color(0, 21, 27));
        txtModelo.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        txtModelo.setForeground(new java.awt.Color(255, 255, 255));
        txtModelo.setBorder(null);
        txtModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModeloActionPerformed(evt);
            }
        });
        jPanel1.add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 360, 30));

        sprModelo.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(sprModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 360, 20));

        lblFondoCRUD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CRUD_ORIGINAL.jpg"))); // NOI18N
        jPanel1.add(lblFondoCRUD, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 470));

        jDesktopPane1.add(jPanel1, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
   
    
    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        //buscamos a vehiculo de la base
        for (int i = 0; i < listaVehiculosBase.size(); i++) {
            
            if (txtPlaca.getText().equalsIgnoreCase(listaVehiculosBase.get(i).getPlaca_Vehiculo())) {
                Boolean valido = false;//creamos una bandera para validar datos
                if (valido = txtColor.getText().matches("^[a-zA-Z]+$")) {
                        if (valido = txtAñoFab.getText().matches("[0-9]{4}")) {
                            Vehiculo encontrado = new Vehiculo(txtPlaca.getText().toUpperCase(), null, null, null, null);//generamos una persona con la cedula para buscar
                            ObjectSet resultado = BaseFinal.get(encontrado);//buscamos en la base
                            if (!resultado.isEmpty()) {
                                resultado.forEach((obj) -> {
                                    BaseFinal.delete(obj);//eliminamos cada objeto encontrado
                                });
                                //una vez eliminado procede a guardar para  "Modificar"
                                guardarVehiculo(BaseFinal, txtPlaca.getText().toUpperCase(), txtModelo.getText().toUpperCase(), (String) cmbMarca.getSelectedItem(), txtColor.getText().toUpperCase(), txtAñoFab.getText().toUpperCase());
                                mostrarDatos(BaseFinal);
                            } else {
                                JOptionPane.showMessageDialog(null, "Vehiculo no encontrada en la BD");
                            }
                            
                        } else {
                            JOptionPane.showMessageDialog(this, "Ingrese un año válido");
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Ingrese un color sin numeros");
                    }
                resetCampos();
                
            }
        }
        //reset campos
        resetCampos();
        //visualizar botones necesarios
        btnBuscar.setVisible(true);
        btnRegistrar.setVisible(true);
        btnModificar.setVisible(false);
        btnEliminar.setVisible(false);
        txtPlaca.setEnabled(true);
        mostrarDatos(BaseFinal);
        
    }//GEN-LAST:event_btnModificarActionPerformed

    public static List<Vehiculo> getListaVehiculosBase(ObjectContainer BaseFinal) {//metodo para obtener la lista de la base
        List<Vehiculo> listaVehiculosBase = new ArrayList<>();
        ObjectSet<Vehiculo> vehiculos = BaseFinal.query(Vehiculo.class);
        for (Vehiculo vehiculo : vehiculos) {
            listaVehiculosBase.add(vehiculo);
        }
        return listaVehiculosBase;
    }
    
    // Nombrar la lista con el uso del metodo anterior
    List<Vehiculo> listaVehiculosBase = getListaVehiculosBase(BaseFinal);
    
    public static void guardarVehiculo(ObjectContainer BaseFinal,String placa_Vehiculo, String modelo_Vehiculo, String marca_Vehiculo, String color_Vehiculo, String anioFabricacion_Vehiculo) {

        Vehiculo vehiculo1 = new Vehiculo(placa_Vehiculo,  modelo_Vehiculo,  marca_Vehiculo,  color_Vehiculo,  anioFabricacion_Vehiculo);

        if (verificarVehiculo(BaseFinal, placa_Vehiculo, null, null, null, null)== 0) {//mandamos a verificar con el codigo
            BaseFinal.set(vehiculo1);
            JOptionPane.showMessageDialog(null,"Vehiculo guardado");
            
        } else {
            JOptionPane.showMessageDialog(null, "Vehiculo ya existe en la BD");
        }
    }
    public static int verificarVehiculo(ObjectContainer BaseFinal,String placa_Vehiculo, String modelo_Vehiculo, String marca_Vehiculo, String color_Vehiculo, String anioFabricacion_Vehiculo) {
        // Crear un nuevo objeto  para usar como plantilla de búsqueda
        Vehiculo BuscarVehi = new Vehiculo(placa_Vehiculo, null, null, null, null);//se ingreesará el valor del codigo y el resto nulo
        // Obtener todos los objetos que coincidan con la plantilla de búsqueda
        ObjectSet resultado = BaseFinal.get(BuscarVehi);//se obtendra resultado que coincida con el codigo
        return resultado.size();//devolvera el numero de coincidencias
    }
    
    
    private void mostrarDatos(ObjectContainer base) {
    jTable1.setEnabled(true);
        //Guardamos en "resultado" todos proveedores de la base de Datos
        ObjectSet<Vehiculo> resultado = base.get(Vehiculo.class);
        //Creo una matriz
        String matriz[][] = new String[resultado.size()][5];
        int i = 0;
        for (Vehiculo miVehi : resultado) {//iteramos en cada elemento de "resultado"
            matriz[i][0] = miVehi.getPlaca_Vehiculo();
            matriz[i][1] = miVehi.getModelo_Vehiculo();
            matriz[i][2] = miVehi.getMarca_Vehiculo();
            matriz[i][3] = miVehi.getColor_Vehiculo();
            matriz[i][4] = miVehi.getAnioFabricacion_Vehiculo();
            i++;
        }

        // datos configurados
        jTable1.setModel(new javax.swing.table.DefaultTableModel(matriz, new String[]{"Placa", "Modelo ","Marca", "Color", "Año Fabricacion"}));
        jTable1.setEnabled(false);
    }
    
    private void resetCampos(){
            txtPlaca.setText("");
            txtModelo.setText("");
            txtColor.setText("");
            txtAñoFab.setText("");
    }
    
    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        //verificamos que no haya el mismo codigo
        Boolean encontrado = false;
        if (listaVehiculosBase.size() > 0) {
            for (int i = 0; i < listaVehiculosBase.size(); i++) {
                if (listaVehiculosBase.get(i).getPlaca_Vehiculo().toUpperCase().equals(txtPlaca.getText())) {
                    JOptionPane.showMessageDialog(this, "YA EXISTE UN VEHICULO CON ESA PLACA");
                    encontrado = true;
                    resetCampos();                    
                }
            }

        }
        Boolean valido = false;//creamos una bandera para validar datos
        if (valido = txtPlaca.getText().toUpperCase().matches("^[A-Z]{3}-\\d{3,4}$")) {//aceptamos 3 letras, un guion y luego 3 a 4 numeros
            if (valido = txtColor.getText().matches("^[a-zA-Z]+$")) {
                if (valido=txtAñoFab.getText().matches("[0-9]{4}")) {
                    // txtPlaca.getText(), txtModelo.getText(), (String)cmbMarca.getSelectedItem(), txtColor.getText(), txtAñoFab.getText()
                    guardarVehiculo(BaseFinal, txtPlaca.getText().toUpperCase(), txtModelo.getText().toUpperCase(), (String)cmbMarca.getSelectedItem(), txtColor.getText().toUpperCase(), txtAñoFab.getText().toUpperCase());
                mostrarDatos(BaseFinal);   
                }else{
                JOptionPane.showMessageDialog(this, "Ingrese un año válido");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Ingrese un color sin numeros");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese una placa Válida");
        }
        resetCampos();
        mostrarDatos(BaseFinal);
    }//GEN-LAST:event_btnRegistrarActionPerformed

    
    public Vehiculo buscarVehiculoporPlaca(ObjectContainer base, String placa) {
        Vehiculo vehiculo = null;
        ObjectSet<Vehiculo> vehiculos = BaseFinal.query(Vehiculo.class);
        for (Vehiculo v : vehiculos) {
            if (v.getPlaca_Vehiculo().equals(placa)) {
                vehiculo = v;
                break;
            }
        }
        return vehiculo;
    }
    
    
    
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // Buscar una Proveedior por codigo
        Vehiculo miVehiculo = buscarVehiculoporPlaca(BaseFinal, txtPlaca.getText().toUpperCase());
        if (miVehiculo != null) {//si encontramos resultados (no seria nulo)
            //recibimos los valores del objeto encontrado y lo pasamos a los campos
            txtPlaca.setText(miVehiculo.getPlaca_Vehiculo());
            txtModelo.setText(miVehiculo.getModelo_Vehiculo());
            cmbMarca.setSelectedItem(miVehiculo.getMarca_Vehiculo());
            txtModelo.setText(miVehiculo.getModelo_Vehiculo());
            txtColor.setText(miVehiculo.getColor_Vehiculo());
            txtAñoFab.setText(miVehiculo.getAnioFabricacion_Vehiculo());
            JOptionPane.showMessageDialog(this, "Vehiculo encontrado");
            //buttons e  identificador
            txtPlaca.setEnabled(false);
            btnRegistrar.setVisible(false);
            btnBuscar.setVisible(false);
            btnEliminar.setVisible(true);
            btnModificar.setVisible(true);
            
        } else {
            JOptionPane.showMessageDialog(this, "No se encontro al vehiculo con placas "+txtPlaca.getText());
        }
        mostrarDatos(BaseFinal);
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    public static void cerrar_BD(ObjectContainer BaseFinal) {
        BaseFinal.close();
        System.exit(0);
    }
    
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.setVisible(false);
        cerrar_BD(BaseFinal);  
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        Vehiculo VehiculoEncontrado = new Vehiculo(txtPlaca.getText().toUpperCase(), null, null, null, null);//generamos un objeto con codigo para buscar
        ObjectSet resultado = BaseFinal.get(VehiculoEncontrado);//buscamos en la base
        Boolean encontrado = false;//bandera para informar que no se encontro coincidencias
        if (!resultado.isEmpty()) {
            int respuesta = JOptionPane.showConfirmDialog(null, "Esta seguro que desea eliminar el vehiculo "+cmbMarca.getSelectedItem()+"  "+ txtModelo.getText() + "?", "Eliminar Vehiculo", JOptionPane.YES_NO_OPTION);
            if (respuesta == JOptionPane.YES_OPTION) {
                // Eliminar la persona
                for (Object obj : resultado) {
                    BaseFinal.delete(obj);//eliminamos cada objeto encontrado
                }
                JOptionPane.showMessageDialog(null, "Vehiculo eliminado");
                encontrado = true;
                mostrarDatos(BaseFinal);
            } else {
                // No eliminar la persona
                JOptionPane.showMessageDialog(null, "Operación cancelada");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Vehiculo no encontrado en la BD");
        }
        //reset campos
        resetCampos();
        //buttons
        txtPlaca.setEnabled(true);
        btnBuscar.setVisible(true);
        btnRegistrar.setVisible(true);
        btnModificar.setVisible(false);
        btnEliminar.setVisible(false);
        mostrarDatos(BaseFinal);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloActionPerformed

    private void txtColorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtColorKeyTyped
        char x = evt.getKeyChar();
        if (Character.isDigit(x)) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingrese solo letras");
        }
    }//GEN-LAST:event_txtColorKeyTyped

    private void txtColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUD_Vehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUD_Vehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUD_Vehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUD_Vehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUD_Vehiculo().setVisible(true);
            }
        });
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbMarca;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAñoFabric;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblFondoCRUD;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblVehiculo;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JSeparator sprAñoFab;
    private javax.swing.JSeparator sprColor;
    private javax.swing.JSeparator sprModelo;
    private javax.swing.JSeparator sprPlaca;
    private javax.swing.JTextField txtAñoFab;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
