
package Vista.Home;

public class Home extends javax.swing.JFrame {

    public Home() {
        initComponents();
        botonesTransparentesIngresar();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dkpHome = new javax.swing.JDesktopPane();
        jplHome = new javax.swing.JPanel();
        btniniciarsesion = new javax.swing.JButton();
        lblBienvenido = new javax.swing.JLabel();
        btncrearcuenta = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dkpHome.setBackground(new java.awt.Color(0, 21, 27));
        dkpHome.setLayout(new java.awt.GridBagLayout());

        jplHome.setBackground(new java.awt.Color(3, 33, 61));
        jplHome.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.blue, java.awt.Color.white, java.awt.Color.blue, java.awt.Color.white));
        jplHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btniniciarsesion.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        btniniciarsesion.setForeground(new java.awt.Color(255, 255, 255));
        btniniciarsesion.setText("INICIAR SESION");
        btniniciarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btniniciarsesionActionPerformed(evt);
            }
        });
        jplHome.add(btniniciarsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 230, 50));

        lblBienvenido.setFont(new java.awt.Font("Eras Bold ITC", 3, 48)); // NOI18N
        lblBienvenido.setForeground(new java.awt.Color(255, 255, 255));
        lblBienvenido.setText("BIENVENIDO ");
        jplHome.add(lblBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 360, 80));

        btncrearcuenta.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        btncrearcuenta.setForeground(new java.awt.Color(255, 255, 255));
        btncrearcuenta.setText("CREAR CUENTA");
        btncrearcuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrearcuentaActionPerformed(evt);
            }
        });
        jplHome.add(btncrearcuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 230, 50));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondohome2.jpg"))); // NOI18N
        lblFondo.setText("jLabel2");
        lblFondo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.blue, java.awt.Color.white, java.awt.Color.blue, java.awt.Color.white));
        jplHome.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 520));

        dkpHome.add(jplHome, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dkpHome)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dkpHome)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btniniciarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btniniciarsesionActionPerformed
      Login1 logincito =new Login1();//crear objeto del jframe
           logincito.setVisible(true);//usar un metodo para mostrar el jframe usando el objeto creado
            this.dispose();//cerrar el jframe
    }//GEN-LAST:event_btniniciarsesionActionPerformed

    private void btncrearcuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrearcuentaActionPerformed
       
    }//GEN-LAST:event_btncrearcuentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Home().setVisible(true);
        });
    }

    public final void botonesTransparentesIngresar() {
        btniniciarsesion.setVisible(true);
        btncrearcuenta.setVisible(true);
        btniniciarsesion.setOpaque(false);
        btniniciarsesion.setContentAreaFilled(false);
        btniniciarsesion.setBorderPainted(false);
        btncrearcuenta.setOpaque(false);
        btncrearcuenta.setContentAreaFilled(false);
        btncrearcuenta.setBorderPainted(false);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncrearcuenta;
    private javax.swing.JButton btniniciarsesion;
    private javax.swing.JDesktopPane dkpHome;
    private javax.swing.JPanel jplHome;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JLabel lblFondo;
    // End of variables declaration//GEN-END:variables
}
